twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        plateform: '%plateform%'
        community: '@App\Service\Community'
        user_group_relation: '@App\Service\UserGroupRelation'
        url_manager: '@App\Service\UrlManager'
